/*
 * Name        drv_OLED_DisplayCommand.h
 * Author      Maksim Golikov (SW developer)
 * Created on: 03 APLIL, 2018
 * Description file contain commands for OLED Display (header file)
 */
#ifndef DRV_DRV_OLED_DISPLAYCOMMAND_H_
#define DRV_DRV_OLED_DISPLAYCOMMAND_H_

enum{
	COMMAND_SET_COLUMN 			=	0x15,
	COMMAND_SET_ROW    			=	0x75,
	COMMAND_WRITE_RAM   		=	0x5C,
	COMMAND_READRAM   			=	0x5D,
	COMMAND_SET_REMAP 			=	0xA0,
	COMMAND_STARTLINE 			=	0xA1,
	COMMAND_DISPLAY_OFFSET 		=	0xA2,
	COMMAND_DISPLAY_ALL_OFF 	=	0xA4,
	COMMAND_DISPLAY_ALL_ON  	=	0xA5,
	COMMAND_NORMAL_DISPLAY 		=	0xA6,
	COMMAND_INVERT_DISPLAY 		=	0xA7,
	COMMAND_FUNCTION_SELECT 	=	0xAB,
	COMMAND_DISPLAY_OFF 		=	0xAE,
	COMMAND_DISPLAY_ON     		=	0xAF,
	COMMAND_PRECHARGE 			=	0xB1,
	COMMAND_DISPLAY_ENHANCE		=	0xB2,
	COMMAND_CLOCK_DIV 			=	0xB3,
	COMMAND_SET_VSL 		    =	0xB4,
	COMMAND_SET_GPIO 			=	0xB5,
	COMMAND_PRECHARGE2 			=	0xB6,
	COMMAND_SETGRAY 			=	0xB8,
	COMMAND_USELUT 			    =	0xB9,
	COMMAND_PRECHARGE_LEVEL 	=	0xBB,
	COMMAND_VCOMH 			    =	0xBE,
	COMMAND_CONTRAST_ABC		=	0xC1,
	COMMAND_CONTRAST_MASTER		=	0xC7,
	COMMAND_MUXRATIO           	=   0xCA,
	COMMAND_COMMAND_LOCK       	=   0xFD,
	COMMAND_HORIZ_SCROLL       	=   0x96,
	COMMAND_STOP_SCROLL        	=   0x9E,
	COMMAND_START_SCROLL       	=   0x9F
};





#endif /* DRV_DRV_OLED_DISPLAYCOMMAND_H_ */
